#!/usr/bin/env bash

###############################################
# Installing AFNI
# This doesn't seem to have version numbers.  Which is upsetting.
# VERSION is the date I downloaded it.
#
# by Owain Kenway, 2015 
#

APPNAME=${APPNAME:-afni}
VERSION=${VERSION:-20181011}
COMPILER_TAG=${COMPILER_TAG:-gnu-4.9.2}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$APPNAME/$VERSION/$COMPILER_TAG}
MD5=${MD5:-522b0feb23057e9362a6f74d2712429a}
SRC_ARCHIVE=${SRC_ARCHIVE:-http://afni.nimh.nih.gov/pub/dist/tgz/afni_src.tgz}

set -e

export PATH=$INSTALL_PREFIX/bin:$PATH

mkdir -p /dev/shm/$APPNAME
temp_dir=`mktemp -d -p /dev/shm/$APPNAME`

cd $temp_dir

wget $SRC_ARCHIVE

CHECKSUM=`md5sum afni_src.tgz| awk '{print $1}'`

if [ "$MD5" == "$CHECKSUM" ]
then
  tar -zxvf afni_src.tgz

  cd afni_src
  cp Makefile.linux_openmp_64 Makefile

# This refers to a directory on the developer's machine.
  sed -i 's|USE_LOCAL_X_TREE = 1||' Makefile

# This sets the install directory
  sed -i 's|INSTALLDIR = ./linux_openmp_64|INSTALLDIR = '$INSTALL_PREFIX'|' Makefile

# This selects the C compiler we've chosen through modules.
  sed -i 's|/usr/bin/gcc|'$CC'|' Makefile

# THis option is no longer supported by GCC.
  sed -i 's|'$CC' -V 34|'$CC'|' Makefile

# These two lines refer to specific library locations on the dev's machine.
  sed -i 's|LGIFTI    = /usr/lib64/libexpat.a|LGIFTI    = -lexpat|' Makefile
  sed -i 's|XLIBS = $(XROOT)/lib64/libXm.a|XLIBS = -lXm|' Makefile

# This is the equivalent of make install.
  make vastness
else
  echo "Hash mismatch."
  echo "Expected: $MD5"
  echo "Got: $CHECKSUM"
fi
