#!/usr/bin/env bash

###############################################
# Installing AMBER
#
# by Owain Kenway, 2015 
#

# You need to purchase a copy of AMBER and put the tar file somehwere.  You 
# should also download the corresponding AmberTools packages.
# Compiles using -xHost.

VERSION=${VERSION:-14}
PARALLEL=${PARALLEL:-""}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/amber}
ABNAME=${ABNAME:-amber-${VERSION}${PARALLEL}}
export AMBERHOME=${INSTALL_PREFIX}/${ABNAME}
SRC_ARCHIVE=${SRC_ARCHIVE:-/shared/ucl/apps/amber/source/Amber${VERSION}.tar.bz2}
TOOLS_SRC_ARCHIVE=${TOOLS_SRC_ARCHIVE:-/shared/ucl/apps/amber/source/AmberTools${VERSION}.tar.bz2}

# module prereqs for building
dirname=$(dirname $0 2>/dev/null)
INCLUDES_DIR=${INCLUDES_DIR:-${dirname}/includes}
source ${INCLUDES_DIR}/require_inc.sh
require gcc-libs
require compilers
require python
require flex

# If intel compilers are loard. MKLROOT will say where MKL is.
export MKL_HOME=$MKLROOT

# AMBER only supports Intel, PGI and GNU compilers.  Work out which we have
# loaded from the tag.

if [[ "${COMPILER_TAG:0:5}" == "intel" ]] 
then
   COMPILER=intel
elif [[ "${COMPILER_TAG:0:3}" == "pgi" ]]
then
   COMPILER=pgi
else
   COMPILER=gnu
fi

set -e

mkdir -p $INSTALL_PREFIX

mkdir -p /dev/shm/amber
temp_dir=`mktemp -d -p /dev/shm/amber`

cd $temp_dir

tar jxvf $SRC_ARCHIVE
tar jxvf $TOOLS_SRC_ARCHIVE

mv amber${VERSION} ${ABNAME}

ln -fsT `pwd`/${ABNAME} $AMBERHOME

cd $AMBERHOME

./configure $PARALLEL --with-python `which python` $COMPILER
source amber.sh
make install

cd $temp_dir
rm $AMBERHOME
mv $ABNAME $AMBERHOME
