#!/usr/bin/env bash

###############################################
# Installing AMBER
#
# by Owain Kenway, 2015 
#

# You need to purchase a copy of AMBER and put the tar file somehwere.  You 
# should also download the corresponding AmberTools packages


VERSION=${VERSION:-14}
PARALLEL=${PARALLEL:-""}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/amber}
export AMBERHOME=${INSTALL_PREFIX}/amber-${VERSION}${PARALLEL}
SRC_ARCHIVE=${SRC_ARCHIVE:-/shared/ucl/apps/amber/source/Amber${VERSION}.tar.bz2}
TOOLS_SRC_ARCHIVE=${TOOLS_SRC_ARCHIVE:-/shared/ucl/apps/amber/source/AmberTools${VERSION}.tar.bz2}

# If intel compilers are loard. MKLROOT will say where MKL is.
export MKL_HOME=$MKLROOT

# AMBER only supports Intel, PGI and GNU compilers.  Work out which we have
# loaded from the tag.

if [[ "${COMPILER_TAG:0:5}" == "intel" ]] 
then
   COMPILER=intel
elif [[ "${COMPILER_TAG:0:3}" == "pgi" ]]
then
   COMPILER=pgi
else
   COMPILER=gnu
fi

set -e

mkdir -p $INSTALL_PREFIX
cd $INSTALL_PREFIX

tar jxvf $SRC_ARCHIVE
tar jxvf $TOOLS_SRC_ARCHIVE

mv amber${VERSION} $AMBERHOME
cd $AMBERHOME

./configure $PARALLEL $COMPILER
source amber.sh
make install
