#!/bin/bash

package_name="thing"
package_version="1.2.3"
# Optional: 
# package_variant=""
package_description="This is a thing that does stuff."

set -o errexit \
    -o nounset \
    -o pipefail

source includes/source_includes.sh

module purge

make_build_env ""

cd "$build_dir"
curl -sLO https://www.example.com/thing-1.2.3.tar.xz

manifest \
	sha256:d2f881a5cc231e2f5a03e86f4584b0438f83edd7598a09d24a21bd8d003e2e01 thing-1.2.3.tar.xz
	

tar -xf thing-1.2.3.tar.xz

cd thing-1.2.3
./configure \
    --prefix="$install_prefix"
make
make check
make install

make_module_v2
chmod a+rX "$module_dir"
post_build_report

