#!/usr/bin/env bash

set -o errexit -o nounset
for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

package_name="cfitsio"
package_version="3370"
src_urls=ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/cfitsio3370.tar.gz
# Optional: 
#package_variant="impi"

actual_file_name=cfitsio3370.tar.gz
actual_file_md5=abebd2d02ba5b0503c633581e3bfa116

require compilers/intel/2015/update2

_env_setup() {
  owd=$(pwd)
  package_label="${package_name}/${package_version}${package_variant:+-${package_variant}}/${COMPILER_TAG}"
  install_prefix=${INSTALL_PREFIX:-/shared/ucl/apps/$package_label}
  build_dir=${BUILD_DIR:-$(mktemp -d -t ${package_name}-build.XXXXXXXX)}
  module_dir=${MODULE_DIR:-$(mktemp -d -t ${package_name}-modules.XXXXXXXX)}
  basename=cfitsio
  cd $build_dir
}

_fetch_files() {
  wget ${actual_file_name:+-O $actual_file_name} $src_urls
  md5sum -c <<<"$actual_file_md5  $actual_file_name"
}

_setup_files() {
  tar -xf $actual_file_name
}

_build() {
  cd ${basename}
  ./configure --prefix=$install_prefix 
  make
  make shared # <- default just builds the static lib
  make testprog
  LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./testprog
  make install
  echo "Installed to: $install_prefix"
}

_prepare_module() {
  make_module -p $install_prefix \
              -n "${package_name}" \
              -c "${package_name}" \
              -o $module_dir/$package_label \
              -r compilers/intel/2015/update2 \
              -w "Adds ${package_name} ${package_version} to your environment."
  echo "Module files put in: $module_dir" >&2
  chmod a+rx $module_dir
}

_clean_up() {
  cd $owd
  if [ -n "$build_dir" ]; then
    rm -Rf ${build_dir}
  fi
}

_env_setup
_fetch_files
_setup_files
_build
_prepare_module
_clean_up

