#!/usr/bin/env bash
_env_setup() {
  package_name="cfitsio"
  PACKAGE_NAME="CFITSIO"
  version="3.370"
  filename="${package_name}3370.tar.gz"
  directory=$package_name
  source_location="http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/$filename"
  compiler=${1:-intel}
  modulefiles=${RSD_MODULES_HOME:-~ccsprsd/modulefiles}


  module swap compilers compilers/$compiler

  INSTALL_PREFIX=${DESTDIR:-/imports/home0/ccsprsd/modules/$package_name/$compiler}
}

_download() {
  cd $temp_dir
  wget $source_location
  tar -xf $filename
}

_configure() {
  cd $temp_dir/$directory
  ./configure --disable-dependency-tracking --prefix=$INSTALL_PREFIX
}

_make() {
  cd $temp_dir/$directory
  make -j8
}

_install() {
  cd $temp_dir/$directory
  make install
}

_modulefile() {
  mkdir -p $modulefiles/$package_name
  cat > $modulefiles/$package_name/$compiler <<EOF
#%Module -*- tcl -*-
##
## dot modulefile
##
proc ModulesHelp { } {
  puts stderr "\tAdds $package_name"
}

module-whatis "$package_name reads FITS files (Flexible Image Transport System)"

set              root              $INSTALL_PREFIX

prereq compilers/$compiler

append-path      LD_RUN_PATH       \$root/lib/
append-path      LD_LIBRARY_PATH   \$root/lib/
append-path      CMAKE_PREFIX_PATH \$root/
append-path      CPATH             \$root/include
append-path      INCLUDE_PATH      \$root/include
append-path      LIBRARY_PATH      \$root/lib
append-path      PKG_CONFIG_PATH   \$root/lib/pkgconfig

setenv           ${PACKAGE_NAME}_LIBRARY_DIR  \$root/lib
setenv           ${PACKAGE_NAME}_INCLUDE_DIR  \$root/include
EOF
}

# loads modules
source /shared/ucl/apps/bin/defmods

for compiler in "gnu" "intel"; do
  temp_dir=`mktemp -d -p /dev/shm`
  _env_setup $compiler
  _download
   _configure
  _make
  _install
  _modulefile
  [[ -d "$temp_dir" ]] && rm -rf $temp_dir || true
done

