#!/usr/bin/env bash

###############################################
# Installing COMSOL 56 for ChemEng
# Set LICSERV= when running the installer. 
#
# Updated January 2021 for Comsol 5.6
# Needs to be insatlled in /shared/ucl/apps/Comsol using group lgcomsol

NAME=${NAME:-Comsol}
VERSION=${VERSION:-56}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/${NAME}/comsol${VERSION}/multiphysics}
SRC_ARCHIVE=${SRC_ARCHIVE:-/shared/ucl/apps/Comsol/Installers/COMSOL${VERSION}_lnx.zip}
LICSERV=${LICSERV:-""}
LICNAME=${LICNAME:-ChemEng}
LICCO=${LICCO:-University College London}
LICTYPE=${LICTYPE:-mph}
COMSOLGROUP=${COMSOLGROUP:-lgcomsol}

set -e

echo ""
echo "**** WARNING: Must use an account that is in the $COMSOLGROUP group to install or chown and"
echo "     chgrp after installation to a suitable account."
echo ""

# Check if LICSERV is empty
if [ -z "$LICSERV" ]
then
    echo "No license server set."
    echo "Please specify LICSERV= when running this buildscript."
    exit 1
fi

mkdir -p "/dev/shm/$NAME"
temp_dir=$(mktemp -d -p "/dev/shm/$NAME")

cd "$temp_dir"

unzip -x "$SRC_ARCHIVE"
cd COMSOL${VERSION}_lnx

# back up and set values in setupconfig
sed -i.bak -e "s|installdir =|installdir = $INSTALL_PREFIX|" setupconfig.ini
sed -i -e "s|showgui = 1|showgui = 0|" setupconfig.ini
sed -i -e "s|agree = 0|agree = 1|" setupconfig.ini
sed -i -e "s|license =|license = $LICSERV|" setupconfig.ini
sed -i -e "s|name =|name = $LICNAME|" setupconfig.ini
sed -i -e "s|company =|company = $LICCO|" setupconfig.ini
sed -i -e "s|lictype =|lictype = $LICTYPE|" setupconfig.ini

sed -i -e "s|startmenushortcuts = 1|startmenushortcuts = 0|" setupconfig.ini
sed -i -e "s|desktopshortcuts = 1|desktopshortcuts = 0|" setupconfig.ini
sed -i -e "s|linuxlauncher = 1|linuxlauncher = 0|" setupconfig.ini
sed -i -e "s|symlinks = 1|symlinks = 0|" setupconfig.ini
sed -i -e "s|fileassoc = 1|fileassoc = 0|" setupconfig.ini
sed -i -e "s|firewall = 1|firewall = 0|" setupconfig.ini

# tell it to put the install config in $temp_dir or it will try to write to ~/.comsol
./setup -s setupconfig.ini -configuration "$temp_dir/comsolconf"

# set permissions to restricted group only
chgrp -Rv "$COMSOLGROUP" "$INSTALL_PREFIX"
chmod o-rx "$INSTALL_PREFIX"

