#!/usr/bin/env bash
_env_setup() {
  package_name="cppunit"
  PACKAGE_NAME="CPPUNIT"
  version="1.13.2"
  filename="$package_name-$version.tar.gz"
  source_location="http://dev-www.libreoffice.org/src/$filename"
  compiler=${1:-intel}
  modulefiles=${RSD_MODULES_HOME:-~ccsprsd/modulefiles}

  temp_dir=`mktemp -d -p /dev/shm`

  module swap compilers compilers/$compiler

  INSTALL_PREFIX=${DESTDIR:-/imports/home0/ccsprsd/modules/$package_name/$compiler}
}

_download() {
  cd $temp_dir
  wget $source_location
  tar -xf $filename
}

_configure() {
  cd $temp_dir/$package_name-$version
  ./configure --disable-dependency-tracking --prefix=$INSTALL_PREFIX
}

_make() {
  cd $temp_dir/$package_name-$version
  make -j8
}

_install() {
  cd $temp_dir/$package_name-$version
  make install
}

_modulefile() {
  mkdir -p $modulefiles/$package_name
  cat > $modulefiles/$package_name/$compiler <<EOF
#%Module -*- tcl -*-
##
## dot modulefile
##
proc ModulesHelp { } {
  puts stderr "\tAdds $package_name"
}

module-whatis "Adds $package_name to your environment"

set              root              $INSTALL_PREFIX

prereq compilers/$compiler

append-path      LD_RUN_PATH       \$root/lib/
append-path      LD_LIBRARY_PATH   \$root/lib/
append-path      CMAKE_PREFIX_PATH \$root/

setenv           ${PACKAGE_NAME}_LIBRARY_DIR  \$root/lib
setenv           ${PACKAGE_NAME}_INCLUDE_DIR  \$root/include
EOF
}

# loads modules
source /shared/ucl/apps/bin/defmods

for compiler in "gnu" "intel"; do
  _env_setup $compiler
  _download
  _configure
  _make
  _install
  _modulefile
done
