#!/usr/bin/env bash
_env_setup() {
  package_name="cppunit"
  version="1.13.2"
  filename="$package_name-$version.tar.gz"
  source_location="http://dev-www.libreoffice.org/src/$filename"
  compiler=${1:-intel}
  modulefiles=${modulefiles:-~ccsprsd/modulefiles}

  temp_dir=`mktemp -d -p /dev/shm`

  MODULE_INIT_PATH=/shared/ucl/apps/bin/defmods
  source $MODULE_INIT_PATH
  module swap compilers compilers/$compiler

  INSTALL_PREFIX=${INSTALL_PREFIX:-/imports/home0/ccsprsd/modules/}/$package_name/$compiler
  export LD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
  export PATH=$INSTALL_PREFIX/bin:$PATH
}

_download() {
  cd $temp_dir
  pwd
  wget $source_location
  tar -xf $filename
}

_configure() {
  cd $temp_dir/$package_name-$version
  ./configure --disable-dependency-tracking --prefix=$INSTALL_PREFIX
}

_make() {
  cd $temp_dir/$package_name-$version
  make -j8
}

_install() {
  cd $temp_dir/$package_name-$version
  make install
}

_modulefile() {
  mkdir -p $modulefiles/$package_name
  cat > $modulefiles/$package_name/$compiler <<EOF
#%Module -*- tcl -*-
##
## dot modulefile
##
proc ModulesHelp { } {
  puts stderr "\tAdds $package_name"
}

module-whatis "Adds $package_name to your environment"

set              root              $INSTALL_PREFIX

conflict cppunit
prereq compilers/$compiler

append-path      LD_RUN_PATH       \$root/lib/
append-path      LD_LIBRARY_PATH   \$root/lib/
append-path      CMAKE_PREFIX_PATH \$root/

setenv           CPPUNIT_LIBRARY_DIR  \$root/lib
setenv           CPPUNIT_INCLUDE_DIR  \$root/include
EOF
}

for compiler in "gnu" "intel"; do
  _env_setup $compiler
  _download
  _configure
  _make
  _install
  _modulefile
done
