#!/usr/bin/env bash
_env_setup() {
  package_name="ctemplate"
  PACKAGE_NAME="CTEMPLATE"
  version="2.3"
  source_dir="$package_name-$version"
  source_location="http://ctemplate.googlecode.com/svn/tags/$package_name-$version/"
  compiler=${1:-intel}
  modulefiles=${modulefiles:-~ccsprsd/modulefiles}

  temp_dir=`mktemp -d -p /dev/shm`

  MODULE_INIT_PATH=/shared/ucl/apps/bin/defmods
  source $MODULE_INIT_PATH
  module load subversion
  module swap compilers compilers/$compiler

  INSTALL_PREFIX=${INSTALL_PREFIX:-/imports/home0/ccsprsd/modules/}/$package_name/$compiler
  export LD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
  export PATH=$INSTALL_PREFIX/bin:$PATH
}

_download() {
  cd $temp_dir
  pwd
  svn co $source_location
}

_configure() {
  cd $temp_dir/$source_dir
  ./configure --disable-dependency-tracking --prefix=$INSTALL_PREFIX
}

_make() {
  cd $temp_dir/$source_dir
  make -j8
}

_install() {
  cd $temp_dir/$source_dir
  make install
}

_modulefile() {
  mkdir -p $modulefiles/$package_name
  cat > $modulefiles/$package_name/$compiler <<EOF
#%Module -*- tcl -*-
##
## dot modulefile
##
proc ModulesHelp { } {
  puts stderr "\tAdds $package_name"
}

module-whatis "Adds $package_name to your environment"

set              root              $INSTALL_PREFIX

conflict $package_name
prereq compilers/$compiler

append-path      PATH              \$root/bin/
append-path      LD_RUN_PATH       \$root/lib/
append-path      LD_LIBRARY_PATH   \$root/lib/
append-path      CMAKE_PREFIX_PATH \$root/

setenv           ${PACKAGE_NAME}_LIBRARY_DIR  \$root/lib
setenv           ${PACKAGE_NAME}_INCLUDE_DIR  \$root/include
EOF
}

for compiler in "gnu" "intel"; do
  _env_setup $compiler
  _download
  _configure
  _make
  _install
  _modulefile
done
