#!/usr/bin/env bash
_env_setup() {
  package_name="cython"
  compiler=${1:-python2}
  version=${2:-0.23.3}
  modulefiles=${RSD_MODULES_HOME:-~ccsprsd/modulefiles}

  temp_dir=`mktemp -d -p /dev/shm`

  module load $compiler
  INSTALL_PREFIX=${DESTDIR:-/imports/home0/ccsprsd/modules/$package_name/$compiler/$version}
  if [ "$compiler" = "python2" ] ; then
    pypath=python2.7
  elif [ "$compiler" = "python3" ] ; then
    pypath=python3.4
  else
    echo "Unknown compiler $compiler"
    exit 1
  fi
}

_install() {
  export PYTHONPATH=$INSTALL_PREFIX/lib/$pypath/site-packages
  export CC=gcc
  export CXX=g++
  export FC=gfortran
  mkdir -p $INSTALL_PREFIX
  pip install $package_name==$version --install-option="--prefix=$INSTALL_PREFIX" -I
}

_modulefile() {
  mkdir -p $modulefiles/$package_name/$compiler
  cat > $modulefiles/$package_name/$compiler/$version <<EOF
#%Module -*- tcl -*-
##
## dot modulefile
##
proc ModulesHelp { } {
  puts stderr "\tAdds $package_name"
}

module-whatis "$package_name is the missing link between C and Python"

set              root              $INSTALL_PREFIX

prereq $compiler
append-path      PYTHONPATH \$root/lib/$pypath/site-packages
EOF
}

# loads modules
source /shared/ucl/apps/bin/defmods

for compiler in "python2" "python3" ; do
  _env_setup $compiler
  # _install
  _modulefile
  module unload $compiler
done
