#!/usr/bin/env bash

set -e

package_name="dftbplus"
package_version="d07f92e3256022a584cab079a9a76aad7b5a8b66"
package_description="DFTB+ is a quantum mechanical simulation software package, based on the Density Functional Tight Binding (DFTB) method."

source includes/source_includes.sh

_env_setup() {
    module purge
    require gcc-libs
    require compilers/intel/2017
    require mpi/intel/2017
    require arpack-ng
    require python2

    make_build_env ""

    package_url="https://github.com/dftbplus/dftbplus.git"
    unpack_dir="dftbplus"
}


_file_setup() {
    cd "$build_dir"

    git clone $package_url
    git submodule update --init --recursive
    
    
}

_pre_build() {
    cd "$unpack_dir"
    git checkout $package_version
    cp sys/make.x86_64-linux-intel ./make.arch
    sed -i.bak "s|mpif90|mpiifort|g" make.arch
    ./utils/get_opt_externals dftd3
    ./utils/get_opt_externals slakos
    cd ..
}

_build() {
    cd "$unpack_dir"
    make WITH_MPI=1 LIB_BLAS=-mkl LNOPT= INSTALLDIR="$install_prefix"
    cd ..
}

_post_build() {
    cd "$unpack_dir"
    # This sed removes two tests that aren't implemented in 17.1 and 
    #  would otherwise mark the test process as failed.
    sed -i -e '/^sockets\/H2O/d' -e '/^sockets\/diamond/d' test/prog/dftb+/tests
    make test

    make INSTALLDIR="$install_prefix" install

    make_module \
        -o "${module_dir}/${package_label}" \
        -p "$install_prefix" \
        -r gcc-libs \
        -r compilers/intel/2017 \
        -r mpi/intel/2017 \
        -r arpack-ng \
        -r python2 \
        -c "$package_name" \
        -w "$package_description"
    cd ..
}

_clean_up() {
    #rm -Rf ${temp_dir:-ERROR_TEMP_DIR_NOT_SET}
    :
}

_env_setup
_file_setup
_pre_build
_build
_post_build
_clean_up

