#!/bin/bash

set -o errexit \
    -o nounset

package_name="dock"
package_version="6.9"
package_variant="reference"


source includes/source_includes.sh

module purge
require gcc-libs/4.9.2
require compilers/gnu/4.9.2

make_build_env ""

owd="$(pwd)"
cd "$build_dir"

cp /shared/ucl/apps/pkg-store/dock.6.9_source.tar.gz ./
tar -xf dock.6.9_source.tar.gz

cd dock6
cd install
./configure gnu
make
cd test
make test
make check
cd ..
make install
# ^-- NB: doesn't install anything to a prefix
#         just copies the binaries to the ./bin directory

# So we have to make the prefix
mkdir -p "$install_prefix"
cd "$build_dir"
cp -r ./dock6/* "$install_prefix/"

chgrp -R legdock "$install_prefix"

make_module \
	-o "$module_dir/$package_label" \
	-c "$package_name" \
	-r "gcc-libs/4.9.2" \
	-p "$install_prefix"

chmod -R a+rX "$module_dir"
echo "Modules installed in: $module_dir"
