#!/usr/bin/env bash
_env_setup() {
  package_name="doxygen"
  version="1.8.10"
  filename="${package_name}-${version}.src.tar.gz"
  directory=$package_name-$version
  source_location="ftp://ftp.stack.nl/pub/users/dimitri/$filename"
  compiler=${1:-intel}
  modulefiles=${RSD_MODULES_HOME:-~ccsprsd/modulefiles}

  module swap compilers compilers/$compiler
  module load bison/$compiler

  INSTALL_PREFIX=${DESTDIR:-/imports/home0/ccsprsd/modules/$package_name/$compiler}
}

_download() {
  cd $temp_dir
  wget $source_location
  tar -xf $filename
}

_configure() {
  builddir=$temp_dir/$directory/build/$compiler
  mkdir -p $builddir
  cd $builddir
  cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
    -DCMAKE_LIBRARY_PATH=$LIBRARY_PATH         \
    -DCMAKE_INCLUDE_PATH=$INCLUDE_PATH         \
    $temp_dir/$directory
}

_make() {
  cd $builddir && make -j8
}

_install() {
  cd $builddir && make install
}

_modulefile() {
  mkdir -p $modulefiles/$package_name
  cat > $modulefiles/$package_name/$compiler <<EOF
#%Module -*- tcl -*-
##
## dot modulefile
##
proc ModulesHelp { } {
  puts stderr "\tAdds $package_name"
}

module-whatis "$package_name is automated API documentation generator"

set              root              $INSTALL_PREFIX

prereq compilers/$compiler
module load bison/$compiler

append-path      LD_RUN_PATH       \$root/lib/
append-path      LD_LIBRARY_PATH   \$root/lib/
append-path      PATH              \$root/bin
EOF
}

# loads modules
source /shared/ucl/apps/bin/defmods

for compiler in "gnu" "intel"; do
  temp_dir=`mktemp -d -p /dev/shm`
  _env_setup $compiler
  _download
   _configure
  _make
  _install
  _modulefile
  [[ -d "$temp_dir" ]] && rm -rf $temp_dir || true
done

