#!/usr/bin/env bash

###############################################
# Installing 
#
# by Owain Kenway, 2015 
#

APPNAME=${APPNAME:-easylausanne}
SRC_ARCHIVE=${SRC_ARCHIVE:-https://github.com/mattcieslak/easy_lausanne}

set -e

export PATH=$INSTALL_PREFIX/bin:$PATH

mkdir -p /dev/shm/$APPNAME
temp_dir=`mktemp -d -p /dev/shm/$APPNAME`

cd $temp_dir

git clone $SRC_ARCHIVE
cd easy_lausanne

VERSION=${VERSION:-`git rev-parse --short HEAD`}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$APPNAME/$VERSION}
mkdir -p $INSTALL_PREFIX/lib/python2.7/site-packages
export PYTHONPATH=$INSTALL_PREFIX/lib/python2.7/site-packages/:$PYTHONPATH

python setup.py install --prefix=$INSTALL_PREFIX

# easy_lausanne's bin scripts have #!/bin/python and so when run can't find
# packages that are part of the recommended bundle. 
cd $INSTALL_PREFIX/bin
sed -i -e "s|#!/bin/python|#!/bin/env python|" atlas_dilate
sed -i -e "s|#!/bin/python|#!/bin/env python|" easy_lausanne

