#!/usr/bin/env bash

###############################################
# Installing Focmec
#
# by Manesh Mistry, 2021
#

APPNAME=${APPNAME:-focmec}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$APPNAME}
set -e

mkdir -p /dev/shm/$APPNAME
temp_dir=`mktemp -d -p /dev/shm/$APPNAME`

cd $temp_dir

wget http://ds.iris.edu/pub/programs/focmec/focmec.tgz

mkdir -p $INSTALL_PREFIX
cd $INSTALL_PREFIX
tar -zxvf $temp_dir/${APPNAME}.tgz
cd $temp_dir/$APPNAME/src
pwd
./build_package 
