#!/usr/bin/env bash

###############################################
# Installing Focmec
#
# by Manesh Mistry, 2021
#

APPNAME=${APPNAME:-focmec}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/focmec}
set -e

mkdir -p /dev/shm/$APPNAME

wget http://ds.iris.edu/pub/programs/focmec/focmec.tgz

mkdir -p $INSTALL_PREFIX
cd $INSTALL_PREFIX
pwd
tar -zxvf ${APPNAME}.tgz
cd focmec/src
pwd
./build_package 
