#!/usr/bin/env bash

###############################################
# Installing Fomec
#
# by Manesh Mistry, 2021
#

APPNAME=${APPNAME:-fomec}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$APPNAME}
SRC_ARCHIVE=${SRC_ARCHIVE:-http://ds.iris.edu/pub/programs/$APPNAME/${APPNAME}.tgz}

set -e

mkdir -p /dev/shm/$APPNAME
temp_dir=`mktemp -d -p /dev/shm/$APPNAME`

cd $temp_dir

wget $SRC_ARCHIVE

mkdir -p $INSTALL_PREFIX
cd $INSTALL_PREFIX
tar -zxvf $temp_dir/${APPNAME}.tgz
cd $temp_dir/$APPNAME/src
pwd
./build_package 
