#!/usr/bin/env bash

###############################################
# Installing Gaussian
#
# by Heather Kelly, 2015
#

NAME=${NAME:-gaussian}
VERSION=${VERSION:-g09-d01}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$VERSION/$COMPILER_TAG}
SRC_ARCHIVE=${SRC_ARCHIVE:-/shared/ucl/apps/gaussian/sources/g09-d01/wkssrc.tgz}
SRC_ARCHIVE_LINDA=${SRC_ARCHIVE_LINDA:-/shared/ucl/apps/gaussian/sources/linda/optlin82.tgz}
GROUP=${GROUP:-legg09}

set -e

mkdir -p /dev/shm/gaussian
temp_dir=`mktemp -d -p /dev/shm/gaussian`

export PATH=$INSTALL_PREFIX/g09:$PATH
export g09root=$temp_dir

cd $g09root
tar -xvf $SRC_ARCHIVE
chgrp -R $GROUP g09

# patch to comment out line that overrides $GV_DIR in g09.profile - we set this in a
# module and it breaks if gview is not in $g09root.
cp /shared/ucl/apps/build_scripts/gaussian-patches/gaussian_g09-d01_profile.patch .
patch -p0 -i gaussian_g09-d01_profile.patch  

cd g09
bsd/install
# Undocumented step that build script doesn't do
cd bsd
pgcc machine.c -o gau-machine
cd ..

# This script does not play well with set -e
set +e
source $g09root/g09/bsd/g09.profile
set -e
bsd/bldg09 2>&1 | tee make.log

# now build Linda version 
cd $g09root/g09
tar -xvf $SRC_ARCHIVE_LINDA 
bsd/install                 
set +e         
source $g09root/g09/bsd/g09.profile    
set -e
# these are missing from g09.profile
mname="`set-mflags x`"
mflags="`set-mflags`"
export mg="${mname} -f bsd/g09.make $mflags"
$mg linda 2>&1 | tee makelinda.log

# Clear out install prefix hopefully fixes permission problems.  If not, check
# out gaussian-g09-d01_fix script.
rm -rf $INSTALL_PREFIX
mkdir -p $INSTALL_PREFIX

cp -r $g09root/g09 $INSTALL_PREFIX
# Linda job setup
cp /shared/ucl/apps/build_scripts/files/gaussian_linda.perl $INSTALL_PREFIX/linda.perl
cd $INSTALL_PREFIX

for a in flc LindaLauncher ntsnet pmbuild vntsnet
do
  echo "Patching ${a}..."
  sed -i.bak 's|'"$temp_dir"'|'"$INSTALL_PREFIX"'|' g09/linda8.2/opteron-linux/bin/$a
done

chgrp -R $GROUP $INSTALL_PREFIX  
chmod -R o-rwx $INSTALL_PREFIX
