#!/usr/bin/env bash

###############################################
# Installing Gaussian
#
# by Heather Kelly, 2015
#

NAME=${NAME:-gaussian}
VERSION=${VERSION:-g09-d01}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$VERSION/$COMPILER_TAG}
MD5=${MD5:-a4f03a2051d3c12856e5ee041a42351a}
SRC_ARCHIVE=${SRC_ARCHIVE:-/home/ccspapp/Software/Gaussian/tar/wkssrc.tgz}
SRC_ARCHIVE_LINDA=${SRC_ARCHIVE_LINDA:-/home/ccspapp/Software/Gaussian/tar/optlin82.tgz}
MD5_LINDA=${MD5_LINDA:-672266813b43fe6af6e6a0d49b13fc7f}
GROUP=${GROUP:-Legg09}

set -e

temp_dir=`mktemp -d -p /dev/shm`

export PATH=$INSTALL_PREFIX/g09:$PATH
export g09root=$temp_dir

CHECKSUM=`md5sum "${SRC_ARCHIVE}"| awk '{print $1}'`
CHECKSUM_LINDA=`md5sum "${SRC_ARCHIVE_LINDA}"| awk '{print $1}'`

if [ "$MD5" == "$CHECKSUM" && "MD5_LINDA" == "$CHECKSUM_LINDA" ]
then

  mkdir -p $INSTALL_PREFIX
  cd $g09root
  tar -xvf $SRC_ARCHIVE
  chgrp -R $GROUP g09

  # patch to comment out line that overrides $GV_DIR in g09.profile - we set this in a
  # module and it breaks if gview is not in $g09root.
  cp /shared/ucl/apps/build_scripts/gaussian-patches/gaussian_g09-d01_profile.patch .
  patch -p0 -i gaussian_g09-d01_profile.patch  

  cd g09
  bsd/install
  # Undocumented step that build script doesn't do
  cd bsd
  pgcc machine.c -o gau-machine
  cd ..
  source $g09root/g09/bsd/g09.profile
  bsd/bldg09 2>&1 | tee make.log

  # now build Linda version 
  cd $g09root/g09
  tar -xvf $SRC_ARCHIVE_LINDA 
  bsd/install                          
  source $g09root/g09/bsd/g09.profile    
  # these are missing from g09.profile
  mname="`set-mflags x`"
  mflags="`set-mflags`"
  alias mg='$mname -f bsd/g09.make $mflags'
  mg linda 2>&1 | tee makelinda.log

  cp -r $g09root/g09 $INSTALL_PREFIX
  # Linda job setup
  cp /shared/ucl/apps/build_scripts/files/gaussian_linda.perl $INSTALL_PREFIX/linda.perl
  cp /shared/ucl/apps/build_scripts/files/linda*.patch .
  patch -p0 -i linda*.patch
  
  chmod -R o-rwx $INSTALL_PREFIX

else
  echo "Hash mismatch."
  echo "Expected: $MD5"
  echo "Got: $CHECKSUM"
fi
