#!/usr/bin/env bash

###############################################
# Installing GaussView 5
#
# by Heather Kelly, 2015
#

NAME=${NAME:-gaussview}
VERSION=${VERSION:-gv5}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/gaussian/$NAME}
MD5=${MD5:-3421ed03204176678bea023a105899f4}
SRC_ARCHIVE=${SRC_ARCHIVE:-/home/ccspapp/Software/Gaussian/tar/$VERSION.tgz}
SRC_SCRIPT=${SRC_SCRIPT:-/home/ccspapp/Software/Gaussian}
GROUP=${GROUP:-legg03}

set -e

CHECKSUM=`md5sum "${SRC_ARCHIVE}"| awk '{print $1}'`

if [ "$MD5" == "$CHECKSUM" ]
then

  mkdir -p $INSTALL_PREFIX
  cd $INSTALL_PREFIX
  tar -xvf $SRC_ARCHIVE

  # Legion specific configuration of gview.csh
  mv $INSTALL_PREFIX/$VERSION/gview.csh $INSTALL_PREFIX/$VERSION/gview.csh.orig
  cp $SRC_SCRIPT/gview.csh $INSTALL_PREFIX/$VERSION
  ln -s gview.csh gview

  chgrp -R $GROUP $VERSION
 
else
  echo "Hash mismatch."
  echo "Expected: $MD5"
  echo "Got: $CHECKSUM"
fi
