#!/usr/bin/env bash

###############################################
# Installing 
#
# by Owain Kenway, 2018
#
set -e

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

require gcc-libs/4.9.2
require git

NAME=${NAME:-illustrate}
VERSION=${VERSION:-896e8d73be0330b8d17f6d899f2d0e546b03da49}
DATE=${DATE:-20190807}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$DATE/$VERSION}

SRC_ARCHIVE=${SRC_ARCHIVE:-https://github.com/ccsb-scripps/Illustrate.git}

rm -rf $INSTALL_PREFIX
mkdir -p $INSTALL_PREFIX

cd $INSTALL_PREFIX

git clone $SRC_ARCHIVE

cd $NAME

git checkout $VERSION

gfortran -o illustrate illustrate.f
