#!/usr/bin/env bash

###############################################
# Installing LAMMPS
#
# by Owain Kenway, 2018
# Updated January 2022 for LAMMPS 29th September 2021 Update 2
#
# Note: Install documentation now recommends CMAKE
#       Using Nvidia HPC SDK module: compilers/nvidia/hpc-sdk/22.1
#
# This is a work in progress script!

NAME=${NAME:-lammps}
TYPE=${TYPE:-basic}
COMPILER_TAG=${COMPILER_TAG:-nvidia-2022-22.1}
VERSION=${VERSION:-29Sep2021_update2}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/lammps/${VERSION}/${TYPE}/$COMPILER_TAG}
SRC_ARCHIVE=${SRC_ARCHIVE:-https://github.com/lammps/lammps/archive/refs/tags/stable_${VERSION}.tar.gz}

WHEREAMI=${WHEREAMI:-$(/shared/ucl/apps/cluster-bin/whereami)}

set -e

export PATH=$INSTALL_PREFIX/bin:$PATH

dirname=$(dirname $0 2>/dev/null || pwd)
INCLUDES_DIR=${INCLUDES_DIR:-${dirname}/includes}
source ${INCLUDES_DIR}/module_maker_inc.sh
source ${INCLUDES_DIR}/require_inc.sh

require compilers/nvidia/hpc-sdk/22.1
require cmake/3.21.1
require python3/recommended

# Not using /dev/shm while sorting out how to build and what options to use.

# mkdir -p /dev/shm/$(whoami)/$NAME
mkdir -p ~/Software/LAMMPS
# temp_dir=$(mktemp -d -p /dev/shm/$(whoami)/$NAME)
temp_dir=$(mktemp -d -p ~/Software/LAMMPS)

cd $temp_dir

wget $SRC_ARCHIVE
tar -xvf stable_${VERSION}.tar.gz
cd lammps-stable_${VERSION}
mkdir -p build
cd build

# Configure for standard build plus shared libraries and build

cmake -C ../cmake/presets/most.cmake -D BUILD_SHARED_LIBS=yes -D CMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} ../cmake
make
make install
