#!/usr/bin/env bash

###############################################
# Installing LAMMPS
#
# by Owain Kenway, 2015 
#

COMPILER_TAG=${COMPILER_TAG:-gnu-4.9.2}
VERSION=${VERSION:-10Feb15}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/lammps/$VERSION/$COMPILER_TAG}
MD5=${MD5:-25a432713a3ad4969fdaaa2551d517ef} 
SRC_ARCHIVE=${SRC_ARCHIVE:-http://lammps.sandia.gov/tars/lammps-${VERSION}.tar.gz}

set -e

export PATH=$INSTALL_PREFIX/bin:$PATH

temp_dir=`mktemp -d`

cd $temp_dir

wget $SRC_ARCHIVE
archive=$(basename "${SRC_ARCHIVE}")

CHECKSUM=`md5sum $archive| awk '{print $1}'`

if [ "$MD5" == "$CHECKSUM" ]
then
  tar -zxvf $archive

  cd lammps-${VERSION}/src

  # Get host machine
  if hostname -A | grep -q legion
  then
    cluster="legion"
  elif hostname -A | grep -q grace
  then
    cluster="grace"
  else
    echo "Unknown machine, exiting: $(hostname -A)"
    exit 1
  fi

  # Copy in appropriate Makefile with correct architecture flags
  cp /shared/ucl/apps/build_scripts/lammps-patches/Makefile.$cluster-${COMPILER_TAG} MAKE/MINE/Makefile.$cluster

# Add some necessary packages that aren't included by default for some reason
  make yes-kspace
  make yes-replica
  make yes-rigid
  make yes-class2

# Make binaries, libraries
  make $cluster

# Put them outside the source tree
  mkdir ../bin
  mv lmp_${cluster} ../bin

# Wipe out our old object files.
  make clean-all
  
# Move install into /shared
  cd ../..
  mkdir -p $INSTALL_PREFIX
  mv lammps-${VERSION} $INSTALL_PREFIX

else
  echo "Hash mismatch."
  echo "Expected: $MD5"
  echo "Got: $CHECKSUM"
fi
