#!/usr/bin/env bash

set -o errexit \
    -o nounset

package_name="metal"
package_version="2011-03-25"
package_description="METAL is a tool for meta-analysis genomewide association scans."
package_url="http://csg.sph.umich.edu/abecasis/Metal/download/generic-metal-${package_version}.tar.gz"

source includes/source_includes.sh
module purge
module load gcc-libs/4.9.2
module load compilers/gnu/4.9.2

make_build_env --tmp-root="/dev/shm"

#mkdir -p "$install_prefix"
#cd "$install_prefix"
cd "$build_dir"

wget "$package_url"

archive=$(basename "${package_url}")

manifest sha1:5b1e497f6d531145d5207d4fd945ea6bf3402af9  "${archive}"

tar -xvf "$archive"

cd generic-metal
# wants a static libm and libz if -static not removed from flags
sed -i.bak -e "s|CFLAGS=-O2 -I./libsrc -I./pdf  -D_FILE_OFFSET_BITS=64 -static|CFLAGS=-O2 -I./libsrc -I./pdf  -D_FILE_OFFSET_BITS=64|" Makefile

make all
make install INSTALLDIR="$install_prefix"

# copy in examples too
cp -r examples "$install_prefix"


make_module_v2 \
    -d \
    -e PATH:"$install_prefix"/gcta_${package_version} 
chmod -R +rX "$module_dir"

rm -Rf "${build_dir:?error: tried to rm blank}" 

post_build_report

