#!/bin/bash

# This script installs the NAG Library Mark 27 for Intel and GCC Compilers.
# Brian Alston September 2019

# Notes: 1) unified NAG library including Fortran and C/C++ bindings
#        2) needs Intel 2019 update 3 or GNU 5.1.0 or later

# Based on nag-fl-mark26-intel_install


VERSION=${VERSION:-27}
PRODUCT=${PRODUCT:-nll6i27dbl}
DOC=${DOC:-mk${VERSION}_doc}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/NAG/fortran-library}
SRC_ARCHIVE=${SRC_ARCHIVE:-https://www.nag.co.uk/downloads/impl/$PRODUCT.tgz}
DOC_ARCHIVE=${DOC_ARCHIVE:-https://www.nag.co.uk/downloads/impl/$DOC.tgz}
MD5_SRC=${MD5_SRC:-84c97689d1510adef991e3fadf5c76f2}
MD5_DOC=${MD5_DOC:-75f6e6f9cef62818316c24b6f3f120f4}

export PATH=$INSTALL_PREFIX/bin:$PATH

temp_dir=`mktemp -d -p /dev/shm`

cd $temp_dir
wget $SRC_ARCHIVE
wget $DOC_ARCHIVE
CHECKSUM_SRC=`md5sum $PRODUCT.tgz | awk '{print $1}'`
CHECKSUM_DOC=`md5sum $DOC.tgz | awk '{print $1}'`

if [ ! "$MD5_SRC" == "$CHECKSUM_SRC" ]
then
    echo "Install Archive Hash mismatch."
    echo "Expected: $MD5_SRC"
    echo "Got: $CHECKSUM_SRC"
    exit 1
fi
if [ ! "$MD5_DOC" == "$CHECKSUM_DOC" ]
then
    echo "Documentation Archive Hash mismatch."
    echo "Expected: $MD5_DOC"
    echo "Got: $CHECKSUM_DOC"
    exit 1
fi

tar xvzf $PRODUCT.tgz
gunzip $DOC.tgz

./install.sh -accept -installdir=$INSTALL_PREFIX \
   -docinstalldir=$INSTALL_PREFIX/doc

