#!/usr/bin/env bash

###############################################
# Installing OasisLMK_ktools 
#
# by Owain Kenway, 2015 
#

APPNAME=${APPNAME:-ktools}
COMPILER_TAG=${COMPILER_TAG:-gnu-4.9.2}
SRC_ARCHIVE=${SRC_ARCHIVE:-https://github.com/OasisLMF/ktools.git}

set -e

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

require gcc-libs/4.9.2
require compilers/gnu/4.9.2
require libbdwgc/7.4.2/gnu-4.9.2
require guile/2.0.11/gnu-4.9.2
require autoconf/2.69
require autogen/5.18.12/gnu-4.9.2
require automake/1.16.1
require pkg-config/0.29.2

mkdir -p /dev/shm/$(whoami)/$APPNAME
temp_dir=`mktemp -d -p /dev/shm/$(whoami)/${APPNAME}`

cd $temp_dir

git clone $SRC_ARCHIVE

cd ${APPNAME}

VERSION=${VERSION:-`git rev-parse --short HEAD`}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$APPNAME/$COMPILER_TAG/$VERSION}

git checkout $VERSION

rm -rf ${INSTALL_PREFIX}
mkdir -p $INSTALL_PREFIX
#cd $INSTALL_PREFIX

#mkdir build
#cd build
#git clone https://github.com/apache/arrow.git -b release-7.0.0
#mkdir -p arrow/cpp/build-release
#cd arrow/cpp/build-release
#cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DARROW_PARQUET=ON -DARROW_BUILD_STATIC=ON -DARROW_OPTIONAL_INSTALL=ON ..
#make -j$(nproc)
#make install

#export PKG_CONFIG_PATH=${INSTALL_PREFIX}/lib64/pkgconfig:${PKG_CONFIG_PATH}

#cd $temp_dir
#cd ${APPNAME}

./autogen.sh
./configure --disable-parquet --prefix=$INSTALL_PREFIX
make
make check
make install



echo "Installed $VERSION"
