#!/usr/bin/env bash

# Build OpenFOAM 7 20200120 patch
# August 2022

# Note: this can take a long time to build (7+ hours) so may be better run from a job.

set -e
export PATH=$INSTALL_PREFIX/bin:$PATH

# dirname=$(dirname $0 2>/dev/null || pwd)
dirname=/shared/ucl/apps/build_scripts
INCLUDES_DIR=${INCLUDES_DIR:-${dirname}/includes}
source ${INCLUDES_DIR}/module_maker_inc.sh
source ${INCLUDES_DIR}/require_inc.sh

WHEREAMI=${WHEREAMI:-$(/shared/ucl/apps/cluster-bin/whereami)}
cluster=$WHEREAMI

# Problems using the GNU 10.2.0 toolchain and OpenMPI 4.0.5 not linking correctly.
# Using GNU 7.3.0 again after building FFTW.

require beta-modules
require gcc-libs/7.3.0
require compilers/gnu/7.3.0
require mpi/openmpi/3.1.4/gnu-7.3.0

NAME=${NAME:-openfoam}
PATCH_VERSION=${VERSION:-20200120}
VERSION=${VRESION:-7}
COMPILER_TAG=${COMPILER_TAG:-gnu-7.3.0}
INSTALL_PREFIX=${INSTALL_PREFIX:-/home/ccaabaa/Scratch/apps/$NAME/${VERSION}-${PATCH_VERSION}/$COMPILER_TAG}
SRC_ARCHIVE=${SRC_ARCHIVE:-http://dl.openfoam.org/source/${VERSION}.${PATCH_VERSION}}
TPSRC_ARCHIVE=${TPSRC_ARCHIVE:-http://dl.openfoam.org/third-party/${VERSION}}

rm -rf $INSTALL_PREFIX

mkdir -p $INSTALL_PREFIX

cd $INSTALL_PREFIX
echo $SRC_ARCHIVE
echo $TPSRC_ARCHIVE
wget -O - ${SRC_ARCHIVE} | tar xvz
wget -O - ${TPSRC_ARCHIVE} | tar xvz

mv OpenFOAM-${VERSION}-${PATCH_VERSION} OpenFOAM-${VERSION}
mv ThirdParty-${VERSION}-version-${VERSION} ThirdParty-${VERSION}

# sed -i.bak "s|FOAM_INST_DIR=\$HOME/\$WM_PROJECT|FOAM_INST_DIR=${INSTALL_PREFIX}\$WM_PROJECT|g" OpenFOAM-${VERSION}/etc/bashrc

set +e
source ${INSTALL_PREFIX}/OpenFOAM-${VERSION}/etc/bashrc
set -e

cd ThirdParty-${VERSION}
./Allwmake

cd ../OpenFOAM-${VERSION}
./Allwmake
