#!/usr/bin/env bash

###############################################
# Installing OpenFOAM-Plus
#
# by Owain Kenway, 2017
#

NAME=${NAME:-openfoamplus}
VERSION=${VERSION:-v1706}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$VERSION/$COMPILER_TAG}
MD5=${MD5:-630d30770f7b54d6809efbf94b7d7c8f}
TPMD5=${TPMD5:-003d38fe3f97ccaa291bafbf94c768eb}

SRC_ARCHIVE=${SRC_ARCHIVE:-https://sourceforge.net/projects/openfoamplus/files/${VERSION}/OpenFOAM-${VERSION}.tgz}
TPSRC_ARCHIVE=${TPSRC_ARCHIVE:-https://sourceforge.net/projects/openfoamplus/files/${VERSION}/ThirdParty-${VERSION}.tgz}

set -e

rm -rf $INSTALL_PREFIX

mkdir -p $INSTALL_PREFIX

cd $INSTALL_PREFIX

wget $SRC_ARCHIVE
wget $TPSRC_ARCHIVE

archive=$(basename "${SRC_ARCHIVE}")
tparchive=$(basename "${TPSRC_ARCHIVE}")

md5sum -c <<< "$MD5 $archive"
md5sum -c <<< "$TPMD5 $tparchive"

tar -xvf $archive
tar -xvf $tparchive

sed -i.bak "s|FOAM_INST_DIR=\$HOME/\$WM_PROJECT|FOAM_INST_DIR=${INSTALL_PREFIX}\$WM_PROJECT|g" OpenFOAM-${VERSION}/etc/bashrc

# Fix for Intel compilers.
if [ "${COMPILER_TAG:0:5}" == "intel" ]
then
  sed -i.bak2 "s|export WM_COMPILER=Gcc|export WM_COMPILER=Icc|g" OpenFOAM-${VERSION}/etc/bashrc
fi

source OpenFOAM-${VERSION}/etc/bashrc

export cgal_version=CGAL-4.9
export boost_version=boost_1_62_0

#cd ThirdParty-v1706/scotch_6.0.3/src

#ln -s ../../etc/wmakeFiles/scotch/Makefile.inc.i686_pc_linux2.shlib-OpenFOAM Makefile.inc

#make scotch

#export LD_LIBRARY_PATH=$INSTALL_PREFIX/ThirdParty-v1706/scotch_6.0.3/lib:LD_LIBRARY_PATH
#export PATH=$INSTALL_PREFIX/ThirdParty-v1706/scotch_6.0.3/bin:$PATH
#export INCLUDE_PATH=$INSTALL_PREFIX/ThirdParty-v1706/scotch_6.0.3/include:$INCLUDE_PATH
#export CPATH=$INSTALL_PREFIX/ThirdParty-v1706/scotch_6.0.3/include:$CPATH
#export CMAKE_PREFIX_PATH=$INSTALL_PREFIX/ThirdParty-v1706/scotch_6.0.3:$CMAKE_PREFIX_PATH


cd $WM_PROJECT_DIR
foamSystemCheck

./Allwmake
