#!/usr/bin/env bash

# Build OpenFOAM v2112 with 64 bit labels to avoid the large mesh problem.
# March 2022

set -e

source includes/source_includes.sh

# starting with the same modules used for v1906

module purge
require beta-modules
require gcc-libs/10.2.0
require compilers/gnu/10.2.0

# Myriad needs extra modules for OpenMPI
if [ "$cluster" == "myriad" ]
then
    require numactl/2.0.12
    require binutils/2.36.1/gnu-10.2.0
    require ucx/1.9.0/gnu-10.2.0
fi

require mpi/openmpi/4.0.5/gnu-10.2.0
require fftw/3.3.9/gnu-10.2.0
require flex/2.5.39

NAME=${NAME:-openfoamplus}
VERSION=${VERSION:-v2112}
COMPILER_TAG=${COMPILER_TAG:-gnu-10.2.0}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/${VERSION}_64/$COMPILER_TAG}
MD5=${MD5:-b6553cfbb6c398e8fe50c96e9e456968}
TPMD5=${TPMD5:-a129907a5ebb88c83580536ce666dbce}

SRC_ARCHIVE=${SRC_ARCHIVE:-https://sourceforge.net/projects/openfoam/files/${VERSION}/OpenFOAM-${VERSION}.tgz}
TPSRC_ARCHIVE=${TPSRC_ARCHIVE:-https://sourceforge.net/projects/openfoam/files/${VERSION}/ThirdParty-${VERSION}.tgz}

rm -rf $INSTALL_PREFIX

mkdir -p $INSTALL_PREFIX

cd $INSTALL_PREFIX

wget --no-check-certificate $SRC_ARCHIVE
wget --no-check-certificate $TPSRC_ARCHIVE

archive=$(basename "${SRC_ARCHIVE}")
tparchive=$(basename "${TPSRC_ARCHIVE}")

md5sum -c <<< "$MD5 $archive"
md5sum -c <<< "$TPMD5 $tparchive"

tar -xvf $archive
tar -xvf $tparchive

sed -i.bak "s|FOAM_INST_DIR=\$HOME/\$WM_PROJECT|FOAM_INST_DIR=${INSTALL_PREFIX}\$WM_PROJECT|g" OpenFOAM-${VERSION}/etc/bashrc

# Fix for Intel compilers.
if [ "${COMPILER_TAG:0:5}" == "intel" ]
then
  sed -i.bak2 "s|export WM_COMPILER=Gcc|export WM_COMPILER=Icc|g" OpenFOAM-${VERSION}/etc/bashrc
fi

# Change label size to 64 bit integers to support large meshes.

sed -i.bak "s|export WM_LABEL_SIZE=32|export WM_LABEL_SIZE=64|g" OpenFOAM-${VERSION}/etc/bashrc

set +e
source ${INSTALL_PREFIX}/OpenFOAM-${VERSION}/etc/bashrc
set -e

export cgal_version=CGAL-4.9
export boost_version=boost_1_62_0

foamSystemCheck

cd $INSTALL_PREFIX/OpenFOAM-v2112
./Allwmake
