#!/usr/bin/env bash

# Package bundle builder for Pypy3

VERSION=${VERSION:-3.0.0}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/pypy/bundles}
PYTHON_VERSION=${PYTHON_VERSION:-3}
TIME_STAMP=$(date +"%s")


# Use local list dir for testing if exists, else the system one
if [[ -d "$(pwd)/lists" ]]; then
    LIST_DIR="$(pwd)/lists"
else
    LIST_DIR="/shared/ucl/apps/build_scripts/lists"
fi

# Disable wheels for some packages
PIPNOBIN=${PIPNOBIN:-:all:}

set -e

# module dependencies:
dirname=$(dirname "$0" 2>/dev/null)
INCLUDES_DIR=${INCLUDES_DIR:-${dirname}/includes}
source "${INCLUDES_DIR}/require_inc.sh"
module purge
require gcc-libs/4.9.2
require compilers/gnu/4.9.2
require pypy3/6.0.0/gnu-4.9.2
require openblas/0.2.14/gnu-4.9.2

mkdir -p "$INSTALL_PREFIX"

cd "$INSTALL_PREFIX"
mkdir "$TIME_STAMP-$PYTHON_VERSION"
cd "$TIME_STAMP-$PYTHON_VERSION"


pypy3 -m venv --system-site-packages venv

source venv/bin/activate

LAPACK=${LAPACK:-/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib/libopenblas.so}
BLAS=${BLAS:-/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib/libopenblas.so}

export LAPACK
export BLAS

pip3 install --upgrade pip

# You'd *think* you could just do this, BUT NO
#  SOME package authors think it's fine to break with an error
#  INSTEAD OF DECLARING THEIR DEPENDENCIES
#pip3 install --no-binary "$PIPNOBIN" -r "$LIST_DIR/pypy-shared.list"
#pip3 install --no-binary "$PIPNOBIN" -r "$LIST_DIR/pypy-3.list"
echo "===="
echo "  Installing lists from $LIST_DIR..."
echo "===="

old_IFS="$IFS"
IFS=$'\n'
for entry in $(cat "$LIST_DIR/pypy-shared.list")
do
   # Ignore blank and comment lines in the lists
   if [[ -n "$entry" ]] && [[ ! "${entry// /}" =~ ^\# ]];
   then
       echo "---- $entry ----"
       # The no-build-isolation part here works around a problem with pip 10's
       #  incomplete implementation of the recent build isolation PEP, that
       #  breaks some Cython-using packages.
       pip3 install --no-build-isolation --no-binary "$PIPNOBIN" "$entry"
   fi
done

for entry in $(cat "$LIST_DIR/pypy-3.list")
do
   # Ignore blank and comment lines in the lists
   if [[ -n "$entry" ]] && [[ ! "${entry// /}" =~ ^\# ]];
   then
       # The no-build-isolation part here works around a problem with pip 10's
       #  incomplete implementation of the recent build isolation PEP, that
       #  breaks some Cython-using packages.
       pip3 install --no-build-isolation --no-binary "$PIPNOBIN" "$entry"
   fi
done
IFS="$old_IFS"

cd ..
ln -Tfs "$TIME_STAMP-$PYTHON_VERSION" "pypy${PYTHON_VERSION}-${VERSION}"
