#!/usr/bin/env bash

###############################################
# Installing Python
#
# by Owain Kenway, 2015 
#

VERSION=${VERSION:-1.0.0}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/python/bundles}
PYTHON_VERSION=${PYTHON_VERSION:-2}
TIME_STAMP=`date +"%s"`

set -e

mkdir -p $INSTALL_PREFIX

cd $INSTALL_PREFIX
mkdir $TIME_STAMP-$PYTHON_VERSION
cd $TIME_STAMP-$PYTHON_VERSION

virtualenv --system-site-packages venv

source venv/bin/activate

export LAPACK=/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib/libopenblas.so
export BLAS=/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib/libopenblas.so

export CVXOPT_BLAS_LIB_DIR=/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib 
export CVXOPT_BLAS_LIB=openblas 
export CVXOPT_LAPACK_LIB_DIR=/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib 
export CVXOPT_LAPACK_LIB=openblas

pip install --upgrade pip

for a in `cat /shared/ucl/apps/build_scripts/lists/python-shared.list`
do
   pip install $a
done

for a in `cat /shared/ucl/apps/build_scripts/lists/python-2.list`
do
   pip install $a
done


cd ..
ln -Tfs $TIME_STAMP-$PYTHON_VERSION python${PYTHON_VERSION} 
