#!/usr/bin/env bash

###############################################
# Installing Python
#
# by Owain Kenway, 2015 
#

VERSION=${VERSION:-2.0.0}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/python/bundles}
PYTHON_VERSION=${PYTHON_VERSION:-2}
TIME_STAMP=`date +"%s"`

# Disable wheels for some packages
PIPNOBIN=${PIPNOBIN:-numpy,scipy}

set -e

# module dependencies:
dirname=$(dirname $0 2>/dev/null)
INCLUDES_DIR=${INCLUDES_DIR:-${dirname}/includes}
source ${INCLUDES_DIR}/require_inc.sh
module purge
require gcc-libs/4.9.2
require compilers/gnu/4.9.2
require python/2.7.12
require openblas/0.2.14/gnu-4.9.2

mkdir -p $INSTALL_PREFIX

cd $INSTALL_PREFIX
mkdir $TIME_STAMP-$PYTHON_VERSION
cd $TIME_STAMP-$PYTHON_VERSION

virtualenv --system-site-packages venv

source venv/bin/activate

LAPACK=${LAPACK:-/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib/libopenblas.so}
BLAS=${BLAS:-/shared/ucl/apps/openblas/0.2.14/gnu-4.9.2/lib/libopenblas.so}


export LAPACK
export BLAS


pip install --upgrade pip

old_IFS="$IFS"
IFS=$'\n'
for entry in `cat /shared/ucl/apps/build_scripts/lists/python-2-2712.list`
do
   if [[ -n "$entry" ]] && [[ ! "${entry// /}" =~ ^\# ]];
   then
       pip install --no-cache-dir --no-binary $PIPNOBIN $entry
   fi
done
IFS="$old_IFS"

cd ..
ln -Tfs $TIME_STAMP-$PYTHON_VERSION python${PYTHON_VERSION}-${VERSION}
