#!/usr/bin/env bash

###############################################
# Installing Python
#
# by Owain Kenway, 2019
#

VERSION=${VERSION:-5.0.0} # 5.0.0 denotes python 3.8.0 version
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/python/bundles}
PYTHON_VERSION=${PYTHON_VERSION_TAG:-38}

TIME_STAMP=`date +"%s"`

set -e

# module dependencies:
dirname=$(dirname $0 2>/dev/null)
INCLUDES_DIR=${INCLUDES_DIR:-${dirname}/includes}
source ${INCLUDES_DIR}/require_inc.sh
require compilers/gnu/4.9.2
require python/3.8.0
require openblas/0.3.2-serial/gnu-4.9.2

mkdir -p $INSTALL_PREFIX

cd $INSTALL_PREFIX
mkdir $TIME_STAMP-$PYTHON_VERSION
cd $TIME_STAMP-$PYTHON_VERSION


# Update pip, setuptools and virtualenv as old versions can cause
# issues with packages due to --system-site-packages.

pip3 install --upgrade setuptools virtualenv pip

virtualenv --system-site-packages venv

source venv/bin/activate

pip3 install --upgrade pip

old_IFS="$IFS"
IFS=$'\n'
for entry in `cat /shared/ucl/apps/build_scripts/lists/python-shared38-fixed.list`
do
   # Ignore blank and comment lines in the lists
   if [[ -n "$entry" ]] && [[ ! "${entry// /}" =~ ^\# ]];
   then
       set +e
       NP_OPENBLAS=`ls /shared/ucl/apps/python/bundles/${TIME_STAMP}-${PYTHON_VERSION}/venv/lib/python3.8/site-packages/numpy/.libs/libopenblas*.so`
       set -e
       LAPACK=${NP_OPENBLAS}
       BLAS=${NP_OPENBLAS}

       export LAPACK
       export BLAS

       pip3 install --no-cache-dir $entry
   fi
done

for entry in `cat /shared/ucl/apps/build_scripts/lists/python-3.list`
do
   # Ignore blank and comment lines in the lists
   if [[ -n "$entry" ]] && [[ ! "${entry// /}" =~ ^\# ]];
   then
       pip3 install --no-cache-dir $entry
   fi
done
IFS="$old_IFS"

cd ..
ln -Tfs $TIME_STAMP-$PYTHON_VERSION python${PYTHON_VERSION}-${VERSION}
