#!/usr/bin/env bash
_env_setup() {
  package_name="PyWavelets"
  compiler=${1:-python2}
  modulefiles=${RSD_MODULES_HOME:-/shared/ucl/apps/rsd/modulefiles}

  module load $pyversion
  export CC=gcc
  export CXX=g++

  INSTALL_PREFIX=${DESTDIR:-/shared/ucl/apps/rsd/modules/$package_name/$pyversion}
  if [ "$pyversion" = "python2" ] ; then
    pypath=python2.7
  elif [ "$pyversion" = "python3" ] ; then
    pypath=python3.4
  else
    echo "Unknown python compiler $pyversion"
    exit 1
  fi
}

_install() {
  export PYTHONPATH=$INSTALL_PREFIX/lib/$pypath/site-packages
  pip install $package_name --install-option="--prefix=$INSTALL_PREFIX" -I
}

_modulefile() {
  mkdir -p $modulefiles/$package_name
  cat > $modulefiles/$package_name/$pyversion <<EOF
#%Module -*- tcl -*-
##
## dot modulefile
##
proc ModulesHelp { } {
  puts stderr "\tAdds $package_name"
}

module-whatis "$package_name is a python package to work with wavelets"

set              root              $INSTALL_PREFIX

prereq $pyversion
append-path      PYTHONPATH \$root/lib/$pypath/site-packages
EOF
}

# loads modules
source /shared/ucl/apps/bin/defmods

for pyversion in "python2" "python3"; do
  _env_setup $pyversion
  _install
  _modulefile
  module unload $pyversion
done
