#!/usr/bin/env bash

###############################################
# Installing qctool
#
# by Owain Kenway, 2018
#

NAME=${NAME:-qctool}
VERSION=${VERSION:-ba5eaa44a62f} # Beta as of 8/8/18
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$VERSION/$COMPILER_TAG}

SRC_ARCHIVE=${SRC_ARCHIVE:-https://gavinband@bitbucket.org/gavinband/qctool}

set -e


dirname=$(dirname $0 2>/dev/null)
INCLUDES_DIR=${INCLUDES_DIR:-${dirname}/includes}
source ${INCLUDES_DIR}/require_inc.sh

require gcc-libs/4.9.2
require compilers/gnu/4.9.2

mkdir -p /dev/shm/${NAME}

temp_dir=`mktemp -d -p /dev/shm/${NAME}`

cd $temp_dir

require python2/recommended # OpenBlas and HG

hg clone -r $VERSION $SRC_ARCHIVE

# Get our python out of the way.
module remove python2
require openblas/0.2.14/gnu-4.9.2

cd qctool

# WAF version number is in the filename because.
WAF=./`ls waf*`

$WAF configure --prefix=$INSTALL_PREFIX
$WAF
$WAF install
