#!/usr/bin/env bash
_env_setup() {
  package_name="spdlog"
  PACKAGE_NAME="SPDLOG"
  directory=$package_name
  source_location="gabime/spdlog"
  compiler=${1:-intel}
  modulefiles=${RSD_MODULES_HOME:-~ccsprsd/modulefiles}

  temp_dir=`mktemp -d -p /dev/shm`

  module load git
  module swap compilers compilers/$compiler

  INSTALL_PREFIX=${DESTDIR:-/imports/home0/ccsprsd/modules/$package_name/$compiler}
}

_download() {
  cd $temp_dir
  git clone git@github.com:$source_location $directory
}

_configure() {
  mkdir -p $temp_dir/$directory/build
  cd $temp_dir/$directory/build
  cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    $temp_dir/$directory
}

_make() {
  cd $temp_dir/$directory/build && make -j8
}

_install() {
  cd $temp_dir/$directory/build && make install
}

_modulefile() {
  mkdir -p $modulefiles/$package_name
  cat > $modulefiles/$package_name/$compiler <<EOF
#%Module -*- tcl -*-
##
## dot modulefile
##
proc ModulesHelp { } {
  puts stderr "\tAdds $package_name"
}

module-whatis "A C++ package for logging"

set              root              $INSTALL_PREFIX

conflict $package_name
prereq compilers/$compiler

append-path      LD_RUN_PATH       \$root/lib/
append-path      LD_LIBRARY_PATH   \$root/lib/
append-path      CMAKE_PREFIX_PATH \$root/

setenv           ${PACKAGE_NAME}_LIBRARY_DIR  \$root/lib
setenv           ${PACKAGE_NAME}_INCLUDE_DIR  \$root/include
EOF
}

# loads modules
source /shared/ucl/apps/bin/defmods

for compiler in "gnu" "intel"; do
  _env_setup $compiler
  _download
  _configure
  _make
  _install
  _modulefile
done
