#!/bin/bash

# This script installs SPM12
# Owain Kenway 2015

# You need to register and download the spm12.zip file and the most up to date 
# patch zip and place it somewhere in your file-system and set the SRC_ARCHIVE 
# variable appropriately.

VERSION=${VERSION:-spm12}
RELEASE=${RELEASE:-r6470}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/spm}
SRC_ARCHIVE=${SRC_ARCHIVE:-/shared/ucl/apps/spm/sources}

set -e

cd $INSTALL_PREFIX
unzip $SRC_ARCHIVE/${VERSION}.zip

cd $VERSION
unzip -o $SRC_ARCHIVE/${VERSION}_updates_${RELEASE}.zip
cd ..

mv ${VERSION} ${VERSION}-${RELEASE}
cd ${VERSION}-${RELEASE}/src

export MATLABPATH=${INSTALL_PREFIX}/${VERSION}-${RELEASE}:${MATLABPATH}

make distclean
make
make install
make external-distclean
make external 
make external-install
