#!/bin/bash

# This script installs SPM12
# Owain Kenway 2015

# Updated January 2020 for latest version of SPM 12 and Matlab R2019b. Note: the
# Jan 2020 version doesn't need a pathc ziz as all updates are included in
# spm12.zip.
#
# Also Matlab R2019b complains that our version of GCC (4.9.2) is too old - using
# version from beta modules instead.
#
# Includes the additional CAT 12 toolbox.

# You need to register and download the spm12.zip file and the most up to date 
# patch zip and place it somewhere in your file-system and set the SRC_ARCHIVE 
# variable appropriately.

VERSION=${VERSION:-spm12}
RELEASE=${RELEASE:-jan2020}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/spm}
SRC_ARCHIVE=${SRC_ARCHIVE:-/shared/ucl/apps/spm/sources}

set -e

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

require beta-modules
require gcc-libs/7.3.0
require compilers/gnu/7.3.0
require xorg-utils/X11R7.7
require matlab/full/r2019b/9.7

cd $INSTALL_PREFIX
unzip $SRC_ARCHIVE/${VERSION}.zip

# cd $VERSION
# unzip -o $SRC_ARCHIVE/${VERSION}_updates_${RELEASE}.zip
# cd ..

mv ${VERSION} ${VERSION}-${RELEASE}
cd ${VERSION}-${RELEASE}/src

export MATLABPATH=${INSTALL_PREFIX}/${VERSION}-${RELEASE}:${MATLABPATH}

make distclean
make
make install
make external-distclean
make external 
make external-install

# Install additional CAT 12 toolbox

cd $SRC_ARCHIVE
wget http://dbm.neuro.uni-jena.de/cat12/cat12_latest.zip
cd $INSTALL_PREFIX/${VERSION}-${RELEASE}/toolbox
unzip -x $SRC_ARCHIVE/cat12_latest.zip
