#!/bin/bash

# This script installs StataMP 16 
# Brian Alston January 2018
# Updated January 2020 for Stata 16
# Updated August 2020 to add older libpng fix needed on mnodern linbux distros
# the fix is from: https://github.com/kylebarron/stata-png-fix

# Based on spm12_install by Owain Kenway

# You need to download the Stata installer from the UCL Software Database
# before running this build script.
# Set the SRC_ARCHIVE & STATA_INSTALLER variables appropriately.

VERSION=${VERSION:-16}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/StataMP}
SRC_ARCHIVE=${SRC_ARCHIVE:-/home/ccspapp/Software/STATA/Stata${VERSION}Linux64.tar.gz}
# SRC_ARCHIVE=${SRC_ARCHIVE:-/home/ccspapp/Software/STATA/Stata${VERSION}Linux64-Legacy.tar.gz}
STATA_INSTALLER=${STATA_INSTALLER:-install}
# EXTRA_FILES=${EXTRA_FILES:-/shared/ucl/apps/build_scripts/files/mathematica_UCL}

dirname=$(dirname $0 2>/dev/null || pwd)
INCLUDES_DIR=${INCLUDES_DIR:-${dirname}/includes}
source ${INCLUDES_DIR}/module_maker_inc.sh
source ${INCLUDES_DIR}/require_inc.sh

require compilers/gnu/4.9.2

if [ ! -f $SRC_ARCHIVE ]
then
    echo ""
    echo "*** ERROR: Cannot find STATA installer archive"
    echo ""
    echo "You need to download the Stata installer from the ISD Software Share:"
    echo ""
    echo "    smb://ad.ucl.ac.uk/GroupFolders/ISD_Software"
    echo ""
    echo "before running this build script."
    echo ""
    exit 1
fi

temp_dir=`mktemp -d -p /dev/shm`
cd $temp_dir

# Unpack installer archive
tar xvzf $SRC_ARCHIVE
INSTALLER_DIR=$temp_dir

# Run the installer from install location.

mkdir -p $INSTALL_PREFIX/stata$VERSION
cd $INSTALL_PREFIX/stata$VERSION
$INSTALLER_DIR/$STATA_INSTALLER <<EOF
y
y
y
EOF

# install Stata libpng fix using method from https://github.com/kylebarron/stata-png-fix

mkdir -p $INSTALL_PREFIX/oldlibs
cd $temp_dir

# These are the old library versions needed by STATA

echo "Install old versions of zlib and libpng needed by STATA ..."

git clone https://github.com/kylebarron/stata-png-fix
wget http://downloads.sourceforge.net/project/libpng/zlib/1.2.3/zlib-1.2.3.tar.gz
wget http://downloads.sourceforge.net/project/libpng/libpng16/older-releases/1.6.2/libpng-1.6.2.tar.gz

tar -xvf zlib-1.2.3.tar.gz
cd zlib-1.2.3
export CFLAGS="-fPIC"
./configure --prefix=$INSTALL_PREFIX/oldlibs
make
make install

cd ..
tar -xvf libpng-1.6.2.tar.gz
cd libpng-1.6.2
export CFLAGS="-I$INSTALL_PREFIX/oldlibs/include -fPIC"
export LDFLAGS="-L$INSTALl_PREFIX/oldlibs/lib"
./configure --prefix=$INSTALL_PREFIX/oldlibs
patch -p1 < ../stata-png-fix/stata-png.patch
make
make install

# install UCL StataMP license for Myriad

echo ""
echo "STATA/MP is only licensed for Myriad so the next step may only be run on Myriad."
echo "You will need the license details supplied by Procurement before continuing."
echo ""
read -p "Do you wish to run the STATA license setup? [y/n] " answer

if [ "$answer" == "y" ]
then
    cd $INSTALL_PREFIX/stata$VERSION
    ./stinit
fi

echo ""
echo "After testing that STATA is working OK, run the internal update"
echo "procedure to bring STATA up to the latest version."
echo ""


