#!/usr/bin/env bash

###############################################
# Installing Adoptium Temurin
#
# by Owain Kenway, 2022
#
set -e

for i in ${includes_dir:=$(dirname $0 2>/dev/null)/includes}/{module_maker,require}_inc.sh; do . $i; done

NAME=${NAME:-temurin}
VERSION=${VERSION:-8u322b06}
INSTALL_PREFIX=${INSTALL_PREFIX:-/shared/ucl/apps/$NAME/$VERSION}
SHA256=${SHA256:-3d62362a78c9412766471b05253507a4cfc212daea5cdf122860173ce902400e}

SRC_ARCHIVE=${SRC_ARCHIVE:-https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u322-b06/OpenJDK8U-jdk_x64_linux_hotspot_8u322b06.tar.gz}


mkdir -p $INSTALL_PREFIX

cd $INSTALL_PREFIX

wget $SRC_ARCHIVE
archive=$(basename "${SRC_ARCHIVE}")

sha256sum -c <<< "$SHA256 $archive"

tar -xvf $archive
