#!/bin/bash

package_name="ubpred"
package_version="1"
package_variant="bin32dist"
package_description="UbPred is a random forest-based predictor of potential ubiquitination sites in proteins."

set -o nounset \
    -o errexit

source includes/source_includes.sh

# No non-system runtime dependencies.
module purge

# We need some slightly weird system tools for this one,
#  check they're here before proceeding.
command -v cpio && \
command -v rpm2cpio

make_build_env ""

cd "$build_dir"

wget http://www.ubpred.org/UbPredDTFileLinux.zip \
     http://www.ubpred.org/MCRInstaller.bin \
     http://mirror.centos.org/centos/7/os/x86_64/Packages/ncurses-libs-5.9-14.20130511.el7_4.i686.rpm \
     http://mirror.centos.org/centos/7/os/x86_64/Packages/libXp-1.0.2-2.1.el7.i686.rpm

manifest \
sha256:aa20cdc3e080e14dfc75a3301e57a9f51650305e960d3ee63cb5b3ca7cfda341  MCRInstaller.bin \
sha256:8d0cfb5e4b29732adfbaa14c0d55ebb5c41fb326c0de139b9e2bd0afba7523d9  UbPredDTFileLinux.zip \
sha256:dd13d39ef9a1f57eca66c515c777f3c4db88dc9329fbf53a9083c92c9387a523  libXp-1.0.2-2.1.el7.i686.rpm \
sha256:7f251dac0fdc4eb4c8e78ae21de44e1cb3e8f380209ed4620cc0394f9c36049e  ncurses-libs-5.9-14.20130511.el7_4.i686.rpm

mkdir -p "$install_prefix"

# Install the 32-bit Matlab runtime
chmod +x MCRInstaller.bin
./MCRInstaller.bin -console <<EOF
1
$install_prefix/mcr
1
1
3
EOF

# Then unpack the RPMs and copy the libraries into the Matlab install v_v
for file in \
    libXp-1.0.2-2.1.el7.i686.rpm \
    ncurses-libs-5.9-14.20130511.el7_4.i686.rpm
do
    rpm2cpio "$file" | cpio -idmv
done

mv usr/lib/* "$install_prefix/mcr/v78/bin/glnx86"


# Then unzip the main file (which is a zipbomb)
mkdir "$install_prefix/ubpred"
cd "$install_prefix/ubpred"
unzip "$build_dir/UbPredDTFileLinux.zip"

# Then set up a wrapper
mkdir "$install_prefix/bin"
cat >"$install_prefix/bin/ubpred.local" <<EOF
#!/bin/bash
# The problem this solves is: UbPred comes with
#  a bunch of .mat files it needs to be able to read
#  from the current working directory.
# This means that you need to run the compiled Matlab
#  file from the directory you unpack all that stuff
#  in.
# So, this tries to wrap that and prefix the filenames
#  you provide so that they'll still go where you expected.

ubpred_main_dir="$install_prefix/ubpred"
ubpred_mcr_dir="$install_prefix/mcr/v78"

EOF

cat >>"$install_prefix/bin/ubpred.local" <<'EOF'

if [[ "$#" -ne 2 ]]; then
    echo "Usage: ubpred.local input_file output_file" >&2
    exit 1
fi

original_working_dir="$(pwd)"

input_file="$1"
output_file="$2"

if [[ "${input_file:0:1}" != "/" ]]; then
    input_file="${original_working_dir}/${input_file}"
fi
if [[ "${output_file:0:1}" != "/" ]]; then
    output_file="${original_working_dir}/${output_file}"
fi

cd "$ubpred_main_dir"
./run_UbPredDTFile.sh "$ubpred_mcr_dir" "$input_file" "$output_file"

EOF
chmod +x "$install_prefix/bin/ubpred.local"
chmod +x "$install_prefix/ubpred/run_UbPredDTFile.sh"
chmod +x "$install_prefix/ubpred/UbPredDTFile"

make_module_v2
chmod -R +rx "$module_dir"

post_build_report

