#!/usr/bin/env sh
#
# Contains default definitions for functions used to install packages from
# source.
#
# Define the variables DESCRIPTION and either SRC_URI or GIT_URI (and
# optionally GIT_BRANCH/GIT_COMMIT) before sourcing this file from your
# scripts.
# Redefine the functions pkg_fetch, src_unpack, src_prepare, src_configure,
# src_compile, src_install and pkg_postinst to customise those steps of the
# installation.  Default definitions for each function that should work in
# the vast majority of cases are provided here.  A main function is then
# defined which calls each function in the order listed above.
#
# See armadillo_6.200.2_install and f2c_install for examples.

source functions/pkg_preinst
source functions/pkg_fetch
source functions/src_unpack
source functions/src_prepare
source functions/src_configure
source functions/src_compile
source functions/src_install
source functions/pkg_postinst

# Prints an optional error message then exits.  Designed to be used within
# package scripts, e.g.:
#   mkdir build || die "Failed to create build directory"
# or:
#   make all || die
die() {
  [ "${1}" ] && echo -e "\033[1;31m${1}\033[0m"
  exit 1
}

# The directory containing this script.
# Works even if this script is called from another directory (i.e. pwd will not
# work).
export CWD="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"

# Check that we have been called with a valid argument
if [ ! ${#} -eq 1 ]
  then
  echo "Usage: ${0##*/} <package_file>"
  exit 1
fi

export P="${1}"
IFS=- read PN PV PR <<< "${P}"
export PN
export PV
export PR

export WORKDIR="${TMPDIR:-/tmp/$(whoami)-install}/${P}"

# ${S} is the build directory
export S="${WORKDIR}/${P}"

source "${CWD}/${1}" || die "Could not find ${1} to install"

if [ -z "${DESCRIPTION}" ] || [ -z "${SRC_URI}" -a -z "${GIT_URI}" -a -z "${SVN_URI}" ]
  then
  die "${P} does not define DESCRIPTION or one of SRC_URI, GIT_URI or SVN_URI"
fi

# ${A} is the archive name, e.g. armadillo-6.200.2.tar.gz
# For git or SVN sources this is blank
if [ "${SRC_URI}" ]
  then
  export A="${SRC_URI##*/}"
else
  export A=""
fi

# ${FILESDIR} is where the patches are stored
export FILESDIR="${CWD}/${PN}-files"

export PREFIX=${PREFIX:-${HOME}}
export DESTDIR="${DESTDIR:-${PREFIX}/modules/${PN}/${PV}/${MODULE_STRING}}"

if [ "${HOME}" == "${WORKDIR}" -o "/" == "${WORKDIR}" ]
  then
  die "Refusing to work in \${HOME} or /"
fi

if [ -d "${WORKDIR}" ]
  then
  rm -rf "${WORKDIR}" || die "Failed to clean working directory ${WORKDIR}"
fi
mkdir -p "${WORKDIR}" || die "Failed to create working directory ${WORKDIR}"

echo -e "\033[1;32mFetching ${A} from ${SRC_URI}\033[0m"
pkg_fetch || die "Failed to fetch sources"
if [ "${A}" ]
  then
  echo -e "\033[1;32mUnpacking ${A} to ${WORKDIR}\033[0m"
  src_unpack || die "Failed to unpack source tarballs"
fi

pushd "${S}" 2>&1 > /dev/null
echo -e "\033[1;32mPatching\033[0m"
src_prepare || die "Failed to prepare sources"
echo -e "\033[1;32mConfiguring\033[0m"
src_configure || die "Failed to configure source"
echo -e "\033[1;32mCompiling source in ${WORKDIR}\033[0m"
src_compile || die "Failed to compile source"
echo -e "\033[1;32mInstalling to ${DESTDIR}\033[0m"
src_install || die "Failed to install source"
echo -e "\033[1;32mPerforming post-installation setup\033[0m"
pkg_postinst || die "Failed to perform post-installation tasks"
popd 2>&1 > /dev/null
