#!/usr/bin/env bash

######################################################################
# Installing a local copy of VASP, no patches, into the user's $HOME
#
# Uses Intel compiler, MKL inc FFTW wrapper, Intel MPI
#
# To run:
# cd /shared/ucl/apps/build_scripts
# ./vasp_individual_install
#
# To run this script with different variables:
# cd /shared/ucl/apps/build_scripts
# VERSION=x.x.x-date INSTALL_PREFIX=/my/install/location SRC_ARCHIVE=/my/vasp/tar ./vasp_individual_install
#

NAME=${NAME:-vasp}
VERSION=${VERSION:-5.4.4-18apr2017}
INSTALL_PREFIX=${INSTALL_PREFIX:-$HOME/$NAME/$VERSION/$COMPILER_TAG}
# we are building in a temporary directory in $HOME/build by default
BUILD_DIR=${BUILD_DIR:-$(mktemp -d -p "$HOME/build" -t "${NAME}-build.XXXXXXXX")}
SRC_ARCHIVE=${SRC_ARCHIVE:-"$HOME/${NAME}-${VERSION}.tgz"}

set -e

# module prereqs for building - checks they are loaded
dirname=$(dirname "$0" 2>/dev/null)
INCLUDES_DIR=${INCLUDES_DIR:-${dirname}/includes}
source "${INCLUDES_DIR}/require_inc.sh"
prereq gcc-libs
prereq compilers/intel
prereq mpi/intel

cd "$BUILD_DIR"

# untar the source into the build directory
tar -xvf "${SRC_ARCHIVE}"

# build and log output
cd "${NAME}-${VERSION}"
cp arch/makefile.include.linux_intel ./makefile.include
make 2>&1 | tee make.log

echo "Build completed"
echo "Installing to $INSTALL_PREFIX"

mkdir -p "${INSTALL_PREFIX}/bin"
cp -v "${BUILD_DIR}/bin/vasp*" "${INSTALL_PREFIX}/bin"

echo "Finished installing."
echo "This was built in $BUILD_DIR - if all went well, you can delete those files"

