#!/usr/bin/env bash
_env_setup() {
  package_name="purify"
  pycompiler=${1:-python2}
  compiler=${2:-intel}
  modulefiles=${RSD_MODULES_HOME:-~ccsprsd/modulefiles}

  if [ "$compiler" = "intel" ] ; then
    fftw="fftw/3.3.4/intel-2015-update2"
  elif [ "$compiler" = "gnu" ] ; then
    fftw="fftw/3.3.4/gnu-4.9.2"
  else
    echo "Unknown compiler $compiler"
    exit 1
  fi

  INSTALL_PREFIX=${DESTDIR:-/imports/home0/ccsprsd/modules/$package_name/$compiler/$pycompiler}
}

_modulefile() {
  mkdir -p $modulefiles/jenkins/$package_name/$compiler/
  cat > $modulefiles/jenkins/$package_name/$compiler/$pycompiler <<EOF
#%Module -*- tcl -*-
##
## dot modulefile
##
proc ModulesHelp { } {
  puts stderr "\tAdds $package_name"
}

module-whatis "Loads all module to work with $purify"

set              root              $INSTALL_PREFIX

module swap compilers compilers/$compiler
module load $pycompiler
module load pytest/$pycompiler
module load cython/$pycompiler
module load $fftw
module load eigen
module load GreatCMakeCookoff
module load cfitsio/$compiler
module load doxygen/$compiler

append-path CMAKE_PREFIX_PATH /shared/ucl/apps/$fftw
if { "$compiler" == "gnu" } {
  module load openblas/0.2.14/gnu-4.9.2
  append-path CMAKE_PREFIX_PATH /shared/ucl/apps/openblas/0.2.14/gnu-4.9.2
}

append-path CMAKE_LIBRARY_PATH $::env(LIBRARY_PATH)
append-path CMAKE_INCLUDE_PATH $::env(INCLUDE_PATH)

if { "$compiler" == "intel" } {
  setenv LDFLAGS "-mkl -lmkl_avx -lmkl_def"
  setenv CFLAGS "-mkl"
}
EOF
}

# loads modules
source /shared/ucl/apps/bin/defmods

for pycompiler in "python2" "python3" ; do
  for compiler in "intel" "gnu" ; do
    _env_setup $pycompiler $compiler
    _modulefile
  done
done
