#!/usr/bin/env bash
_env_setup() {
  package_name="purify"
  pycompiler=${1:-python2}
  compiler=${2:-intel}
  modulefiles=${RSD_MODULES_HOME:-/shared/ucl/apps/rsd/modulefiles}

  if [ "$compiler" = "intel" ] ; then
    ccompiler="intel/2015/update2"
    boost="boost-1.60.0-intel-16.0.0-xh6vyvufvac7ei34sa7xa6trehet2b6f"
  elif [ "$compiler" = "gnu" ] ; then
    fftw="fftw/3.3.4/gnu-4.9.2"
    ccompiler="gnu/4.9.2"
    boost="boost-1.60.0-gcc-4.9.2-x4eb7s2lw2porc3fixnkymist2xkrn65"
  else
    echo "Unknown compiler $compiler"
    exit 1
  fi

  INSTALL_PREFIX=${DESTDIR:-/shared/ucl/apps/rsd/modules/$package_name/$compiler/$pycompiler}
}

_modulefile() {
  mkdir -p $modulefiles/jenkins/$package_name/$compiler/
  cat > $modulefiles/jenkins/$package_name/$compiler/$pycompiler <<EOF
#%Module -*- tcl -*-
##
## dot modulefile
##
proc ModulesHelp { } {
  puts stderr "\tAdds $package_name"
}

module-whatis "Loads all module to work with $purify"

set              root              $INSTALL_PREFIX

module swap compilers compilers/$ccompiler
module load jenkins/sopt/$compiler/$pycompiler
module load $boost
module load doxygen-1.8.10-gcc-4.9.2-g4iiglbvyt5trinty5gi7quegmg23qbw

append-path CMAKE_PREFIX_PATH /shared/ucl/apps/$fftw
if { "$compiler" == "gnu" } {
  module load openblas/0.2.14/gnu-4.9.2
  append-path CMAKE_PREFIX_PATH /shared/ucl/apps/openblas/0.2.14/gnu-4.9.2
}

append-path CMAKE_LIBRARY_PATH $::env(LIBRARY_PATH)
append-path CMAKE_INCLUDE_PATH $::env(INCLUDE_PATH)

if { "$compiler" == "intel" } {
  setenv LDFLAGS "-mkl -lmkl_avx -lmkl_def"
  setenv CFLAGS "-mkl"
}
EOF
}

# loads modules
source /shared/ucl/apps/bin/defmods

for pycompiler in "python2" "python3" ; do
  for compiler in "intel" "gnu" ; do
    _env_setup $pycompiler $compiler
    _modulefile
  done
done
