#!/usr/bin/env bash
_env_setup() {
  package_name="sopt"
  pycompiler=${1:-python2}
  compiler=${2:-intel}
  modulefiles=${RSD_MODULES_HOME:-/shared/ucl/apps/rsd/modulefiles}

  if [ "$compiler" = "intel" ] ; then
    ccompiler="intel/2015/update2"
    fftw="fftw/3.3.4/intel-2015-update2"
    cfitsio="cfitsio-3.370-intel-16.0.0-tafgqoy666tdxop74lhl7bfp7c7wig2b"
    eigen="Eigen-3.2.7-intel-16.0.0-75wkblk6tcedg7zknnjq6ttyh5qfyerc"
    spdlog="spdlog-dev-intel-16.0.0-bo7aljmuwwayqacwf6fc76bwzkei73mh"
    gbenchmark="gbenchmark-1.0.0-intel-16.0.0-d73sn5qo5p47w4pkcbmzkh23zx77mo3y"
  elif [ "$compiler" = "gnu" ] ; then
    ccompiler="gnu/4.9.2"
    fftw="fftw/3.3.4/gnu-4.9.2"
    cfitsio="cfitsio-3.370-gcc-4.9.2-3zknqa3qmewhfdir5lllsvsyubrukldg"
    eigen="Eigen-3.2.7-gcc-4.9.2-yljnptvwpmsa7awoeowaizjplgpgriur"
    spdlog="spdlog-dev-gcc-4.9.2-fpkicawlycnnnnvr3zteddxjhudr2me2"
    gbenchmark="gbenchmark-1.0.0-gcc-4.9.2-xfckdztmph5qa2lpwv5bnljbvr33boln"
  else
    echo "Unknown compiler $compiler"
    exit 1
  fi

  INSTALL_PREFIX=${DESTDIR:-/shared/ucl/apps/rsd/modules/$package_name/$compiler/$pycompiler}
}

_modulefile() {
  mkdir -p $modulefiles/jenkins/$package_name/$compiler/
  cat > $modulefiles/jenkins/$package_name/$compiler/$pycompiler <<EOF
#%Module -*- tcl -*-
##
## dot modulefile
##
proc ModulesHelp { } {
  puts stderr "\tAdds $package_name"
}

module-whatis "Loads all module to work with $purify"

set              root              $INSTALL_PREFIX

module swap compilers compilers/$ccompiler
module load $pycompiler $cfitsio $spdlog $gbenchmark $fftw $eigen
module load PyWavelets/$pycompiler

append-path CMAKE_PREFIX_PATH /shared/ucl/apps/$fftw
if { "$compiler" == "gnu" } {
  module load openblas/0.2.14/gnu-4.9.2
  append-path CMAKE_PREFIX_PATH /shared/ucl/apps/openblas/0.2.14/gnu-4.9.2
}
append-path CMAKE_LIBRARY_PATH $::env(LIBRARY_PATH)
append-path CMAKE_INCLUDE_PATH $::env(INCLUDE_PATH)
EOF
}

# loads modules
source /shared/ucl/apps/bin/defmods

for pycompiler in "python2" "python3" ; do
  for compiler in "intel" "gnu" ; do
    _env_setup $pycompiler $compiler
    _modulefile
  done
done
